playing with some coverage checks in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,7 +12,24 @@ jobs:
       with:
         go-version: ${{ matrix.go-version }}
     - uses: actions/checkout@v3
-    - run: go test ./...
+    - env:
+      TESTCOVERAGE_THRESHOLD: 70
+    - if: matrix.os == 'ubuntu-latest'
+      run: |
+        echo "Quality Gate: checking test coverage is above threshold..."
+        echo "Threshold    : $TESTCOVERAGE_THRESHOLD %"
+        totalCoverage=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
+        echo "Current test coverage: $totalCoverage %"
+        if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+            echo "PASS"
+        else
+            echo "Current test coverage is below threshold. Please add more unit tests."
+            echo "Failed"
+            exit 1
+        fi
+    - else:
+      run:
+        go test -v -cover ./...
 
   # setup caching in between builds to improve incremental builds
   test-cache:
